In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [2]:
import pandas

In [7]:
df1 = pandas.read_csv("supermarkets.csv")
df1.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [9]:
df2 = pandas.read_json("supermarkets.json")
df2.set_index("ID")

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [21]:
df3 = pandas.read_excel("supermarkets.xlsx", sheetname=0)
df3.set_index("ID")

Address           City             State Country Supermarket Name  \
ID                                                                              
1      3666 21st St  San Francisco          CA 94114     USA          Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA      Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA      Super River   
4      3995 23rd St  San Francisco          CA 94114     USA       Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA          Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA       Richvalley   

    Number of Employees  
ID                       
1                     8  
2                    15  
3                    25  
4                    10  
5                    12  
6                    20

In [14]:
df4 = pandas.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [27]:
df5 = pandas.read_csv("supermarkets-semi-colons.txt", sep = ";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [28]:
df5 = df5.set_index("Address")

In [34]:
df5

ID           City             State Country          Name  \
Address                                                                      
3666 21st St      1  San Francisco          CA 94114     USA       Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA   Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA   Super River   
3995 23rd St      4  San Francisco          CA 94114     USA    Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA       Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA    Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [54]:
list(df5.loc[:,"City"])

['San Francisco',
 'San Francisco',
 'San Francisco',
 'San Francisco',
 'San Francisco',
 'San Francisco']

In [55]:
df5

ID           City             State Country          Name  \
Address                                                                      
3666 21st St      1  San Francisco          CA 94114     USA       Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA   Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA   Super River   
3995 23rd St      4  San Francisco          CA 94114     USA    Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA       Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA    Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [65]:
df5.iloc[3, 1:4]

City       San Francisco
State           CA 94114
Country              USA
Name: 3995 23rd St, dtype: object

In [66]:
df5.ix[3, 1:4]

City       San Francisco
State           CA 94114
Country              USA
Name: 3995 23rd St, dtype: object

In [89]:
df5.columns

Index(['ID', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')

In [95]:
df5["Continent"] = df5.shape[0]*["Taipei"]

In [109]:
df5["test"][0] = "ttt"

/usr/local/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [115]:
df5["Continent"] = df5["Country"]

In [116]:
df5

ID           City             State Country          Name  \
Address                                                                      
3666 21st St      1  San Francisco          CA 94114     USA       Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA   Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA   Super River   
3995 23rd St      4  San Francisco          CA 94114     USA    Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA       Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA    Richvalley   

                 Employees Continent     test  
Address                                        
3666 21st St             8       USA      ttt  
735 Dolores St          15       USA  Taipei2  
332 Hill St             25       USA  Taipei2  
3995 23rd St            10       USA  Taipei2  
1056 Sanchez St         12       USA  Taipei2  
551 Alvarado St         20       USA  Taipei2

In [117]:
df5_t = df5.T

In [119]:
df5_t

Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
ID                     1              2                 3              4   
City       San Francisco  San Francisco     San Francisco  San Francisco   
State           CA 94114       CA 94119  California 94114       CA 94114   
Country              USA            USA               USA            USA   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
Employees              8             15                25             10   
Continent            USA            USA               USA            USA   
test                 ttt        Taipei2           Taipei2        Taipei2   

Address   1056 Sanchez St 551 Alvarado St  
ID                      5               6  
City        San Francisco   San Francisco  
State          California        CA 94114  
Country               USA             USA  
Name              Sanchez      Richvalley  
Employees              12              20  
Continent             USA             USA  
test              Taipei2         Taipei2

In [122]:
df5_t["My Address"] = ["1","2",10,7,"3","4","5","6"]

In [124]:
df5 = df5_t.T

In [126]:
df5

ID           City             State Country          Name  \
Address                                                                     
3666 21st St     1  San Francisco          CA 94114     USA       Madeira   
735 Dolores St   2  San Francisco          CA 94119     USA   Bready Shop   
332 Hill St      3  San Francisco  California 94114     USA   Super River   
3995 23rd St     4  San Francisco          CA 94114     USA    Ben's Shop   
1056 Sanchez St  5  San Francisco        California     USA       Sanchez   
551 Alvarado St  6  San Francisco          CA 94114     USA    Richvalley   
My Address       1              2                10       7             3   

                Employees Continent     test  
Address                                       
3666 21st St            8       USA      ttt  
735 Dolores St         15       USA  Taipei2  
332 Hill St            25       USA  Taipei2  
3995 23rd St           10       USA  Taipei2  
1056 Sanchez St        12       USA  Taipei2  
551 Alvarado St        20       USA  Taipei2  
My Address              4         5        6

In [138]:
df5.ix["My Address2"]

ID            1
City          2
State        10
Country       7
Name          3
Employees     4
Continent     5
test          6
Name: My Address, dtype: object

In [140]:
df5.ix["My Address2"] = ["1","2",10,7,"3","4","5","6"]

In [143]:
df5.ix["My Address3"] = ["2","2",10,7,"3","4","5","6"]

In [147]:
df5.ix["My Address3"]["City"] = "fefe"

In [149]:
df5

ID           City             State Country          Name  \
Address                                                                     
3666 21st St     1  San Francisco          CA 94114     USA       Madeira   
735 Dolores St   2  San Francisco          CA 94119     USA   Bready Shop   
332 Hill St      3  San Francisco  California 94114     USA   Super River   
3995 23rd St     4  San Francisco          CA 94114     USA    Ben's Shop   
1056 Sanchez St  5  San Francisco        California     USA       Sanchez   
551 Alvarado St  6  San Francisco          CA 94114     USA    Richvalley   
My Address       1              2                10       7             3   
My Address2      1              2                10       7             3   
My Address3      2           fefe                10       7             3   

                Employees Continent     test  
Address                                       
3666 21st St            8       USA      ttt  
735 Dolores St         15       USA  Taipei2  
332 Hill St            25       USA  Taipei2  
3995 23rd St           10       USA  Taipei2  
1056 Sanchez St        12       USA  Taipei2  
551 Alvarado St        20       USA  Taipei2  
My Address              4         5        6  
My Address2             4         5        6  
My Address3             4         5        6

In [151]:
import geopy

In [152]:
dir(geopy)

['ArcGIS',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeFarm',
 'GeocoderDotUS',
 'GoogleV3',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'NaviData',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Photon',
 'Point',
 'What3Words',
 'YahooPlaceFinder',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'units',
 'util']

In [154]:
from geopy.geocoders import Nominatim

In [155]:
nom = Nominatim()

In [156]:
nom.geocode("Taiwan")

Location(臺灣, (23.9739374, 120.9820179, 0.0))

In [157]:
nom.geocode("Japan")

Location(日本, (36.5748441, 139.2394179, 0.0))

In [167]:
n = nom.geocode("Taiwan")

In [168]:
n.latitude

23.9739374

In [169]:
n.longitude

120.9820179

In [170]:
import pandas
df = pandas.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [171]:
df["Address"] = df["Address"] + ", " + df["City"] + ", " + df["State"] + ", " + df["Country"]

In [172]:
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [ ]:
df["Coordinates"] = df["Address"].apply(nom.geocode)


In [178]:
df["Coordinates"][0]

Location(3666, 21st Street, Noe Valley, SF, California, 94114, United States of America, (37.756488877551, -122.429343346939, 0.0))

In [182]:
df["Latitude"] = df["Coordinates"].apply(lambda x: x.latitude if x != None else None)

df["Longitide"] = df.Coordinates.apply(lambda x: x.longitude if x != None else None)

In [183]:
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitide  
0  (3666, 21st Street, Noe Valley, SF, California...  37.756489 -122.429343  
1                                               None        NaN         NaN  
2  (332, Hill Street, Noe Valley, SF, California,...  37.755725 -122.428601  
3  (3995, 23rd Street, Noe Valley, SF, California...  37.752965 -122.431714  
4  (1056, Sanchez Street, Noe Valley, SF, Califor...  37.752146 -122.429815  
5  (551, Alvarado Street, Noe Valley, SF, Califor...  37.753673 -122.433220

In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [2]:
import numpy
ny = numpy.arange(27)

In [3]:
ny

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(ny)

numpy.ndarray

In [6]:
range(5)

range(0, 5)

In [7]:
print(ny)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [9]:
ny.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [10]:
print(ny)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [15]:
ny.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [17]:
m

array([[123, 12, 123, 12, 33], [], []], dtype=object)

In [18]:
type([[123,12,123,12,33],[],[]])

list

In [19]:
print(m)

[[123, 12, 123, 12, 33] [] []]


In [20]:
type(m)

numpy.ndarray

In [29]:
m.reshape(3,1)

array([[[123, 12, 123, 12, 33]],
       [[]],
       [[]]], dtype=object)

In [33]:
import cv2

In [58]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [62]:
im_g2 =[[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]]

In [63]:
im_g2

[[187, 158, 104, 121, 143],
 [198, 125, 255, 255, 147],
 [209, 134, 255, 97, 182]]

In [74]:
im_g[2,3]

97

In [75]:
im_g2[0:2]

[[187, 158, 104, 121, 143], [198, 125, 255, 255, 147]]

In [80]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [86]:
for i in im_g.T.flat:
    print(i)

187
198
209
158
125
134
104
255
255
121
255
97
143
147
182


In [87]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [90]:
ims = numpy.hstack((im_g, im_g, im_g))

In [93]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [95]:
ims2 = numpy.vstack((im_g, im_g, im_g))
print(ims2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [104]:
lst = numpy.hsplit(ims2, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [106]:
lst = numpy.vsplit(ims2, 3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [107]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)